### ISSUE TITLE
The result dropped when I swith "current gt" to "previous gt"

### ISSUE THREAD

**Issue by HaozheQi** [SilvioGiancola/ShapeCompletion3DTracking#6]
HELLO, I noticed that input parameter “--reference_BB” use the "current_gt" value in your code, which I think may use the knowledge of current frame. So I change it to "previous_gt" and get a falling resut of 57/65, when using "current_gt" the result is 76/81, I wander if I do something wrong or the algorithm would have a performance degradation?

**Comment by SilvioGiancola** [comment]
Dear @ZeyangZhang1, 

The "--reference_BB" parameter is indeed "current_gt" for the exhaustive search. See our paper for more details of how the exhaustive search is defined, in particular section 3.4:

![image](https://user-images.githubusercontent.com/7395008/66850098-c7e47000-ef80-11e9-89e6-86f60c829cd5.png)

As we mentioned in our paper, we argue that in order to have the ground truth candidate in our simulated exhaustive search, we are constrained to center the grid search space around it. As a consequence, we use the knowledge of the current frame. Results drop when centering the exhaustive grid search around the "previous_gt" as the "current_gt" is not contained in the list of candidates provided by the grid search. 

Such limitation of using knowledge of the current frame only applies for the exhaustive search. A more realistic search space is shown in Table 5 with the "Kalman Filtering", centered on the previous results, and could most probably be improved. Also, note that "previous_gt" also uses GT information - not from the current frame, but from the previous frame -. I would recommend you to center the grid search around the previous results using "previous_results" for the parameter "--reference_BB" as defined [here](https://github.com/SilvioGiancola/ShapeCompletion3DTracking/blob/b4648ac67e9ba16ef986c58e021c6b52ae6ffd4e/code/train.py#L328), but the results will drop below 57/65.

Hope that answered your issue!
